packages:
  - packages/*

catalog:
  "@restatedev/restate-sdk": ^1.8.0
  "@restatedev/restate-sdk-clients": ^1.8.0
  "@restatedev/restate-sdk-testcontainers": ^1.8.0
  xstate: ^5.20.1

onlyBuiltDependencies:
  - cpu-features
  - esbuild
  - protobufjs
  - ssh2

overrides:
  "@eslint/plugin-kit@<0.3.4": ">=0.3.4"
  tar-fs@>=2.0.0 <2.1.4: ">=2.1.4"
  tar-fs@>=3.0.0 <3.1.1: ">=3.1.1"
  tmp@<=0.2.3: ">=0.2.4"
  vite@>=7.0.0 <=7.0.6: ">=7.0.7"
